Django/demo02/booktest/urls.py
from django.conf.urls import url
from .views import *
app_name="booktest"
urlpatterns=[
    url(r'^index/$',index,name="index"),
    url(r'^list/$',list,name="list"),
    url(r'^detail/(\d+)/$',detail,name="detail"),
    url(r'^deletehero/(\d+)/$',deletehero,name="deletehero"),
    url(r'^deletebook/(\d+)/$',deletebook,name="deletebook"),
    url(r'^addhero/(\d+)/$',addhero,name="addhero"),
    url(r'^addbook$',addbook,name="addbook")
]

Django/demo02/demo02/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('polls/',include("polls.urls",namespace="polls")),
    url('booktest/',include("booktest.urls",namespace="booktest"))
]

Django/demo02/polls/urls.py
from django.conf.urls import url
from .views import *

app_name="polls"

urlpatterns=[
    url(r'^index/$',index,name="index"),
    url(r'^detail/(\d+)/$',detail,name="detail"),
    url(r'^result/(\d+)/$',result,name="result"),
]

Django/demo02/booktest/models.py
from django.db import models

# Create your models here.

class BookInfo(models.Model):
    title=models.CharField(max_length=20)
    pub_date=models.DateField(auto_now=True)
    def __str__(self):
        return self.title
class heroInfo(models.Model):
    name=models.CharField(max_length=20)
    gender=models.CharField(max_length=5,choices=(  ("man","男"),("woman","女") ))
    content=models.CharField(max_length=100)
    book=models.ForeignKey(BookInfo,on_delete=models.CASCADE)
    def __str__(self):
        return self.name

Django/demo02/polls/models.py
from django.db import models

# Create your models here.
class Questions(models.Model):
    desc=models.CharField(max_length=20)
    desc_time=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.desc

class Choices(models.Model):
    desc=models.CharField(max_length=10)
    votes=models.IntegerField(default=0)
    question=models.ForeignKey(Questions,on_delete=models.CASCADE)
    def __str__(self):
        return self.desc

Django/demo02/booktest/views.py
from django.shortcuts import render,reverse,redirect
from .models import *
from django.http import HttpResponse
# Create your views here.
def index(request):

    return render(request,"booktest/index.html")

def list(request):
    books = BookInfo.objects.all
    return render(request,"booktest/list.html",{"books":books})


def detail(request,id):
    book=BookInfo.objects.get(pk=id)
    return render(request,"booktest/detail.html",{"book":book})

def deletehero(request,id):
    hero=heroInfo.objects.get(pk=id)
    bookid=hero.book.id
    hero.delete()
    # return render(request, "booktest/detail.html", {"hero": hero})
    # return HttpResponse("删除成功")
    return redirect(reverse("booktest:detail",args=(bookid,)))

def deletebook(request,id):
    book=BookInfo.objects.get(pk=id)
    book.delete()
    # return HttpResponse("删除成功")
    return redirect(reverse("booktest:list"))

def addhero(request,id):
    book = BookInfo.objects.get(pk=id)
    if request.method=="GET":
        return render(request, "booktest/addhero.html", {"book": book})
    elif request.method=="POST":
        name=request.POST.get("name")
        content=request.POST.get("content")
        hero=heroInfo()
        hero.name=name
        hero.content=content
        hero.book=book
        hero.save()
        return redirect(reverse("booktest:detail",args=(id,)))
def addbook(request):
    if request.method=="GET":
        return render(request, "booktest/addbook.html")
    elif request.method=="POST":
        title=request.POST.get("title")
        book=BookInfo()
        book.title=title
        book.save()
        return redirect(reverse("booktest:list"))

Django/demo02/polls/views.py
from django.shortcuts import render
from .models import Questions,Choices
from django.http import HttpResponse


# Create your views here.

def index(request):
    questions=Questions.objects.all
    return render(request,"polls/index.html",{"questions":questions})


def detail(request,id):
    question = Questions.objects.get(pk=id)
    if request.method=="GET":
        return render(request,"polls/detail.html",{"question":question})
    elif request.method=="POST":
        choiceid=request.POST.get("choice")
        print(choiceid)
        choice=Choices.objects.get(pk=choiceid)
        print(choice)
        choice.votes+=1
        choice.save()
        return render(request,"polls/result.html",{"question":question})
def result(request,id):
    question = Questions.objects.get(pk=id)
    return  render(request,"polls/result.html")

Django/demo02/templates/booktest/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <form class="form-horizontal" method="post">
          <div class="form-group">
            <label for="booktitle" class="col-sm-2 control-label">书籍名字</label>
            <div class="col-sm-5">
              <input type="text" class="form-control" name="title" id="booktitle" placeholder="名字">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-5">
              <button type="submit" class="btn btn-default">添加</button>
            </div>
          </div>
</form>
</div>

</body>
</html>

Django/demo02/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
     <!--加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</head>
<body>
    <div class="container">
        <h2>当前书籍：{{book.title}}</h2>
        <form class="form-horizontal" method="post">
          <div class="form-group">
            <label for="username" class="col-sm-2 control-label">名字</label>
            <div class="col-sm-5">
              <input type="text" class="form-control" name="name" id="username" placeholder="名字">
            </div>
          </div>
          <div class="form-group">
            <label for="content" class="col-sm-2 control-label">技能</label>
            <div class="col-sm-5">
              <input type="text" class="form-control" name="content" id="content" placeholder="技能">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-5">
              <button type="submit" class="btn btn-default">添加</button>
            </div>
          </div>
</form>
    </div>

</body>
</html>

Django/demo02/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情</title>
</head>
<body>
    <div class="container">
        <h2>当前书籍：{{book.title}}</h2>
        {% if book.heroinfo_set.count %}
            <ul>
            {% for h in book.heroinfo_set.all %}
                <li>{{forloop.counter}} {{h.name}}----{{h.content}}
                    <a href="{% url 'booktest:deletehero' h.id %}">删除</a>
                </li>
            {% endfor %}
            </ul>
        {% else %}
                <li>没有角色</li>
        {% endif %}
        <a href="{% url 'booktest:addhero' book.id %}">添加角色</a>
</div>

</body>
</html>

Django/demo02/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
     <!--加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</head>
<body>
<div class="container">

    <a href="{% url 'booktest:list' %}">列表页</a>
</div>


</body>
</html>

Django/demo02/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表</title>
</head>
</head>
<body>
<div class="container">
    <ul>
        {% for book in books %}
        <li>{{forloop.counter}}<a href="{% url 'booktest:detail' book.id %}" >{{book.title}}</a>
            <a href="{% url 'booktest:deletebook' book.id %}">删除</a>
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'booktest:addbook' %}">添加书籍</a>
</div>

</body>
</html>

Django/demo02/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
</head>
<body>
    <div class="container">
        <h2>当前问题：{{question.dsc}}</h2>
        <form action="{% url 'polls:detail' question.id %}" method="post">
            {% for c in question.choices_set.all %}
            {% if forloop.counter == 1 %}
                <li><input type="radio" name="choice"  value="{{c.id}}" checked>{{c.desc}}</li>
            {% else %}
                <li><input type="radio" name="choice" value="{{c.id}}"  >{{c.desc}}</li>
            {% endif %}
            {% endfor %}
            <input type="submit" value="投票">
        </form>

    </div>

</body>
</html>

Django/demo02/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
    <div class="container">
        <h2>问题列表</h2>
        {% if questions %}
            {% for q in questions %}

            <li>{{forloop.counter}}<a href="{% url 'polls:detail' q.id %}" >{{ q.desc }}</a></li>

            {% empty %}
                <li>没有查找到问题</li>
            {% endfor %}
        {% else %}
            <li>没有问题可以投票</li>
        {% endif %}

    </div>

</body>
</html>

Django/demo02/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>结果页</title>
</head>
<body>
    <diV class="container">
        <h2>当前问题：{{question.desc}}</h2>
        <ul>
            {% for c in question.choices_set.all %}
            <li>{{forloop.counter}}{{c.desc}}---{{c.votes}}</li>
            {% endfor %}
        </ul>
        <a href="{% url 'polls:index' %}">回到首页</a>
    </diV>

</body>
</html>